version: '3.8'

services:
  database:
    image: postgres:13
    container_name: projectX
    env_file:
      - .env
    ports:
      - "5432:5433"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
    driver: bridge
